#include <iostream>
#include <cmath>
#include <string>

using std::cin;
using std::cout;
using std::endl;
using std::string;

int main() {
int FirstSeedNumber = 0;
int SecondSeedNumber = 0;
int ThirdSeedNumber = 0;
int FourthSeedNumber = 0;
int FifthSeedNumber = 0;
int SixthSeedNumber = 0;
int SeventhSeedNumber = 0;
int EighthSeedNumber = 0;
int NinthSeedNumber = 0;
int TenthSeedNumber = 0;
int EleventhSeedNumber = 0;
int TwelvethSeedNumber = 0;
int ThirteenthSeedNumber = 0;
int FourteenthSeedNumber = 0;
int FifteenthSeedNumber = 0;
int SixteenthSeedNumber = 0;
int SeventeenthSeedNumber = 0;
int EighteenthSeedNumber = 0;
int NineteenthSeedNumber = 0;
int TwentiethSeedNumber = 0;
int TwentyFirstSeedNumber = 0;
int TwentySecondSeedNumber = 0;
int TwentyThirdSeedNumber = 0;
int TwentyFourthSeedNumber = 0;
int TwentyFifthSeedNumber = 0;
int TwentySixthSeedNumber = 0;
int TwentySeventhSeedNumber = 0;
int TwentyEighthSeedNumber = 0;
int TwentyNinthSeedNumber = 0;
int ThirtiethSeedNumber = 0;
int ThirtyFirstSeedNumber = 0;
int ThirtySecondSeedNumber = 0;
int ThirtyThirdSeedNumber = 0;
int ThirtyFourthSeedNumber = 0;
int ThirtyFifthSeedNumber = 0;
int ThirtySixthSeedNumber = 0;
int ThirtySeventhSeedNumber = 0;
int ThirtyEighthSeedNumber = 0;
int ThirtyNinthSeedNumber = 0;
int FortiethSeedNumber = 0;
int FortyFirstSeedNumber = 0;
int FortySecondSeedNumber = 0;
int FortyThirdSeedNumber = 0;
int FortyFourthSeedNumber = 0;
int FortyFifthSeedNumber = 0;
int FortySixthSeedNumber = 0;
int FortySeventhSeedNumber = 0;
int FortyEighthSeedNumber = 0;
int FortyNinthSeedNumber = 0;
int FiftiethSeedNumber = 0;
int FiftyFirstSeedNumber = 0;
int FiftySecondSeedNumber = 0;
int FiftyThirdSeedNumber = 0;
int FiftyFourthSeedNumber = 0;
int FiftyFifthSeedNumber = 0;
int FiftySixthSeedNumber = 0;
int FiftySeventhSeedNumber = 0;
int FiftyEighthSeedNumber = 0;
int FiftyNinthSeedNumber = 0;
int SixtiethSeedNumber = 0;
int SixtyFirstSeedNumber = 0;
int SixtySecondSeedNumber = 0;
int SixtyThirdSeedNumber = 0;
int SixtyFourthSeedNumber = 0;
int SixtyFifthSeedNumber = 0;
int SixtySixthSeedNumber = 0;
int SixtySeventhSeedNumber = 0;
int SixtyEighthSeedNumber = 0;
int SixtyNinthSeedNumber = 0;
int SeventiethSeedNumber = 0;
int SeventyFirstSeedNumber = 0;
int SeventySecondSeedNumber = 0;
int SeventyThirdSeedNumber = 0;
int SeventyFourthSeedNumber = 0;
int SeventyFifthSeedNumber = 0;
int SeventySixthSeedNumber = 0;
int SeventySeventhSeedNumber = 0;
int SeventyEighthSeedNumber = 0;
int SeventyNinthSeedNumber = 0;
int EightiethSeedNumber = 0;
int EightyFirstSeedNumber = 0;
int EightySecondSeedNumber = 0;
int EightyThirdSeedNumber = 0;
int EightyFourthSeedNumber = 0;
int EightyFifthSeedNumber = 0;
int EightySixthSeedNumber = 0;
int EightySeventhSeedNumber = 0;
int EightyEighthSeedNumber = 0;
int EightyNinthSeedNumber = 0;
int NintiethSeedNumber = 0;
int NintyFirstSeedNumber = 0;
int NintySecondSeedNumber = 0;
int NintyThirdSeedNumber = 0;
int NintyFourthSeedNumber = 0;
int NintyFifthSeedNumber = 0;
int NintySixthSeedNumber = 0;
int NintySeventhSeedNumber = 0;
int NintyEighthSeedNumber = 0;
int NintyNinthSeedNumber = 0;
int OneHundredthSeedNumber = 0;
}
