#include <iostream>
#include <cmath>
#include <ctime>
#include <string>
#include <array>
#include <vector>
#include <cstdint>
#include <sstream>
#include <memory>
#include <memory_resource>
#include <new>

using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::vector;
using std::getline;
using std::array;

int main() {
string FirstSeed;
string SecondSeed;
string ThirdSeed;
string FourthSeed;
string FifthSeed;
string SixthSeed;
string SeventhSeed;
string EighthSeed;
string NinthSeed;
string TenthSeed;
string EleventhSeed;
string TwelvethSeed;
string ThirteenthSeed;
string FourteenthSeed;
string FifteenthSeed;
string SixteenthSeed;
string SeventeenthSeed;
string EighteenthSeed;
string NineteenthSeed;
string TwentiethSeed;
string TwentyFirstSeed;
string TwentySecondSeed;
string TwentyThirdSeed;
string TwentyFourthSeed;
string TwentyFifthSeed;
string TwentySixthSeed;
string TwentySeventhSeed;
string TwentyEighthSeed;
string TwentyNinthSeed;
string ThirtiethSeed;
string ThirtyFirstSeed;
string ThirtySecondSeed;
string ThirtyThirdSeed;
string ThirtyFourthSeed;
string ThirtyFifthSeed;
string ThirtySixthSeed;
string ThirtySeventhSeed;
string ThirtyEighthSeed;
string ThirtyNinthSeed;
string FortiethSeed;
string FortyFirstSeed;
string FortySecondSeed;
string FortyThirdSeed;
string FortyFourthSeed;
string FortyFifthSeed;
string FortySixthSeed;
string FortySeventhSeed;
string FortyEighthSeed;
string FortyNinthSeed;
string FiftiethSeed;
string FiftyFirstSeed;
string FiftySecondSeed;
string FiftyThirdSeed;
string FiftyFourthSeed;
string FiftyFifthSeed;
string FiftySixthSeed;
string FiftySeventhSeed;
string FiftyEighthSeed;
string FiftyNinthSeed;
string SixtiethSeed;
string SixtyFirstSeed;
string SixtySecondSeed;
string SixtyThirdSeed;
string SixtyFourthSeed;
string SixtyFifthSeed;
string SixtySixthSeed;
string SixtySeventhSeed;
string SixtyEighthSeed;
string SixtyNinthSeed;
string SeventiethSeed;
string SeventyFirstSeed;
string SeventySecondSeed;
string SeventyThirdSeed;
string SeventyFourthSeed;
string SeventyFifthSeed;
string SeventySixthSeed;
string SeventySeventhSeed;
string SeventyEighthSeed;
string SeventyNinthSeed;
string EightiethSeed;
string EightyFirstSeed;
string EightySecondSeed;
string EightyThirdSeed;
string EightyFourthSeed;
string EightyFifthSeed;
string EightySixthSeed;
string EightySeventhSeed;
string EightyEighthSeed;
string EightyNinthSeed;
string NintiethSeed;
string NintyFirstSeed;
string NintySecondSeed;
string NintyThirdSeed;
string NintyFourthSeed;
string NintyFifthSeed;
string NintySixthSeed;
string NintySeventhSeed;
string NintyEighthSeed;
string NintyNinthSeed;
string OneHundredthSeed;
}
